name: Build and Push Docker Image

on:
  workflow_call

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: CHECK DATA
        run: |
          echo ${{ env.REGISTRY }}
          echo ${{ env.IMAGE_NAME }}
          echo ${{ github.actor }}

      - name: build and push backend docker image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest